services:
   run-tests:
     image: automationexercise-image:latest
     container_name: automationexercise_container
     volumes:
      - ./:/usr/workspace
     command: bash -c "pytest -n 2 --alluredir=allure-results"
