name: UI Tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: automationexercise-image:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run UI-tests via docker-compose
        run: docker compose up --exit-code-from run-tests
